### ISSUE TITLE
Create a Kata for making a meme using a template from assets

### ISSUE THREAD

**Issue by ezratkim** [thoughtstem/Summer2019#169]
**./my-memes-kc/?category? Kata #** 
Create a meme using one of the templates in the assets folder

**EASY:**
Create an image of your meme template
```racket
#lang fundamentals
(require 2htdp/universe)
;in order for this code to work, the .rkt file needs to be saved in the same directory as the assets folder that the .png file is saved
(define image (bitmap "./assets/pipe.png")) ;put the filename that you want instead of pipe.png
```
**MEDIUM:**
Add text to a created image

**HARD:**
Add text, shapes, designs, and/or other images to a created image

_Add any other prompts and code with assigned difficulties that you come up with_

**Comment by Ann-Ryan** [comment]
There is a testing-meme-curriculum.rkt file in the meme-katas folder that is an example of what a meme kata could look like. The katas should go into this folder, either on the same document or separate documents.

**Comment by kristynamason** [comment]
I've added a more detailed example of exactly what a meme kata should look like. Please take a look and try HARD: by adding some additional shapes, designs, and/or other images to your newly created meme.
