### ISSUE TITLE
Put these Katas into KataCollections/my-data-sci-katas in the correct format.

### ISSUE THREAD

**Issue by DrewKeirn** [thoughtstem/Summer2019#192]
Note: See katas in other folders for examples on formatting. You may need to create another folder within this directory.

#lang racket
(require plot)

**Easy** - Plot a exponential graph.

(plot (function sqr -2 1))

**Medium** - Plot a dotted exponential graph.

(plot (function sqr -2 2
                #:style 'dot))

**Hard** - Plot two exponential graphs with a proper labels and differing styles on the same graph.

(plot (list (axes)
              (function sqr -2 2
                        #:color 2)))

**Comment by sandorac** [comment]
I think I did it correctly, not 100% sure.
