### ISSUE TITLE
Format my-memes-katas

### ISSUE THREAD

**Issue by Titan-Ngo** [thoughtstem/Summer2019#287]
__Remember to pull for the latest version!__

You will be updating two files throughout this whole process:
- `Summer2019/Languages/my-meme-lang/examples.rkt`
- `Summer2019/Kata-Collections/my-meme-katas/katas.rkt`

You will be getting the files in `my-meme-lang/Examples/` and copy/pasting each one into the
__examples.rkt__ file inside of different definitions. You will need to make this file. Please refer to this file inside of `my-game-lang/` for help and formatting.

Then for each kata definition you made, you will go inside of `my-meme-katas/katas.rkt` in the __katas__ definition and add in the stimuli for that kata __using the name that you made__. Follow the formatting guidelines. 

If you need more help, first refer to the bottom of the `Summer2019/README.md`, then a similar file called `Summer2019/my-game-katas/katas.rkt`. Otherwise, ask me.

To check if you did it successfully, run `./scripts/build-katas` inside of `Summer2019/Kata-Collections/my-meme-katas/`. The website should pop up in Chrome with your katas.

You can do it!

**Comment by slpeeler** [comment]
I worked on this issue in branch formatMemes
