### ISSUE TITLE
Help me aggregate git learning resources

### ISSUE THREAD

**Issue by srfoster** [thoughtstem/Summer2019#29]
Post links below

**Comment by meghakhelgi** [comment]
http://git.huit.harvard.edu/guide/

**Comment by arthimat** [comment]
https://guides.github.com/introduction/git-handbook/

**Comment by meghakhelgi** [comment]
https://readwrite.com/2013/09/30/understanding-github-a-journey-for-beginners-part-1/

**Comment by slpeeler** [comment]
big guide https://sp19.datastructur.es/materials/guides/using-git.html

**Comment by slpeeler** [comment]
basic git tutorial for basic prompts https://www.youtube.com/watch?v=KoPxeLqWRTY

**Comment by slpeeler** [comment]
image that shows basic git flow https://sp19.datastructur.es/materials/guides/img/file-status.png

**Comment by dschulz474** [comment]
https://www.freecodecamp.org/news/learn-the-basics-of-git-in-under-10-minutes-da548267cc91/

**Comment by arthimat** [comment]
This website helped a lot with learning command prompt git basics:  https://confluence.atlassian.com/bitbucketserver/basic-git-commands-776639767.html

**Comment by dschulz474** [comment]
https://www.freecodecamp.org/news/learn-the-basics-of-git-in-under-10-minutes-da548267cc91/

**Comment by slpeeler** [comment]
video for branching https://www.youtube.com/watch?v=QV0kVNvkMxc

**Comment by slpeeler** [comment]
video for merging https://www.youtube.com/watch?v=XX-Kct0PfFc

**Comment by slpeeler** [comment]
For merging:

https://www.atlassian.com/git/tutorials/using-branches/git-merge this is the guide

https://www.atlassian.com/git/tutorials/learn-branching-with-bitbucket-cloud this is the interactive tutorial

**Comment by dschulz474** [comment]
my reccomendation: http://git.huit.harvard.edu/guide/

**Comment by meghakhelgi** [comment]
my recommendation: https://www.freecodecamp.org/news/learn-the-basics-of-git-in-under-10-minutes-da548267cc91/

**Comment by slpeeler** [comment]
my recommendation: http://git.huit.harvard.edu/guide/
