### ISSUE TITLE
Delete Repetitive Kata

### ISSUE THREAD

**Issue by Ann-Ryan** [thoughtstem/Summer2019#494]
It's in the web development katas. It may or may not be in Languages/my-web-lang/examples.rkt twice. Have fun.

**Comment by Ann-Ryan** [comment]
Everything in Languages/my-web-lang/examples.rkt and Kata-Collections/my-web-katas/katas.rkt is connected.

**Comment by ezratkim** [comment]
As far as I can tell, each kata group does something a little different (ie. ordered vs unordered) and although similar, I think that they should be kept in
