### ISSUE TITLE
Add example output to katas doc A

### ISSUE THREAD

**Issue by srfoster** [thoughtstem/Summer2019#61]
Notice how this (fantastic) doc interleaves its example code with the output of that code:

https://docs.racket-lang.org/teachpack/2htdpimage.html

Add similar example output to new-katas-a.scrbl

**Comment by Ann-Ryan** [comment]
Don't do this by manually uploading pictures, there is a way to make the code run and put its output right onto the webpage. This is a challenging ticket.

**Comment by Melody-Ruth** [comment]
We did it! (Preethi, Ambre, and Melody)
